# Generated by Django 4.1.3 on 2022-12-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMundial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='dorsal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='seleccion',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
