# Generated by Django 4.1.3 on 2022-12-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMundial', '0002_jugador_dorsal_jugador_seleccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreestadio', models.CharField(blank=True, max_length=20, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lafinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versus', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha', models.DateField()),
                ('horario', models.TimeField()),
                ('resultado', models.CharField(blank=True, max_length=20, null=True)),
                ('campeon', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partidos_cuartos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versus', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha', models.DateField()),
                ('horario', models.TimeField()),
                ('resultado', models.CharField(blank=True, max_length=20, null=True)),
                ('ganador', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partidos_octavos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versus', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha', models.DateField()),
                ('horario', models.TimeField()),
                ('resultado', models.CharField(blank=True, max_length=20, null=True)),
                ('ganador', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partidos_semis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versus', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha', models.DateField()),
                ('horario', models.TimeField()),
                ('resultado', models.CharField(blank=True, max_length=20, null=True)),
                ('ganador', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Selecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seleccion', models.CharField(blank=True, max_length=30, null=True)),
                ('banderacolor', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='jugador',
            name='clubactual',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='seleccion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
