# Generated by Django 4.1.3 on 2022-12-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMundial', '0003_estadios_lafinal_partidos_cuartos_partidos_octavos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GrupoA', models.CharField(blank=True, max_length=40, null=True)),
                ('GrupoB', models.CharField(blank=True, max_length=40, null=True)),
                ('GrupoC', models.CharField(blank=True, max_length=40, null=True)),
                ('GrupoD', models.CharField(blank=True, max_length=40, null=True)),
                ('GrupoE', models.CharField(blank=True, max_length=40, null=True)),
                ('GrupoF', models.CharField(blank=True, max_length=40, null=True)),
                ('GrupoG', models.CharField(blank=True, max_length=40, null=True)),
                ('GrupoH', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playoffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versus', models.CharField(blank=True, max_length=60, null=True)),
                ('estadio', models.CharField(blank=True, max_length=20, null=True)),
                ('arbitro', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha', models.DateField()),
                ('horario', models.TimeField()),
                ('resultado', models.CharField(blank=True, max_length=20, null=True)),
                ('ganador', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lafinal',
            name='arbitro',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lafinal',
            name='estadio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='partidos_cuartos',
            name='arbitro',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partidos_cuartos',
            name='estadio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='partidos_octavos',
            name='arbitro',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partidos_octavos',
            name='estadio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='partidos_semis',
            name='arbitro',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partidos_semis',
            name='estadio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
