# Generated by Django 4.1.3 on 2022-12-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMundial', '0004_arbitros_grupos_playoffs_lafinal_arbitro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lafinal',
            name='resultado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partidos_cuartos',
            name='resultado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partidos_octavos',
            name='resultado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partidos_semis',
            name='resultado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
