# Generated by Django 4.1.3 on 2022-12-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMundial', '0005_alter_lafinal_resultado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playoffs',
            name='grupo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
