# Generated by Django 4.1.3 on 2022-12-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMundial', '0006_playoffs_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='clubactual',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lafinal',
            name='resultado',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='partidos_cuartos',
            name='resultado',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='partidos_octavos',
            name='resultado',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='partidos_semis',
            name='resultado',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='playoffs',
            name='resultado',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='selecciones',
            name='banderacolor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
