# Generated by Django 4.1.3 on 2022-12-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMundial', '0007_alter_jugador_clubactual_alter_lafinal_resultado_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Playoffs',
            new_name='Fase_grupos',
        ),
        migrations.RenameModel(
            old_name='Lafinal',
            new_name='La_final',
        ),
    ]
