# Generated by Django 4.1.4 on 2022-12-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMundial', '0009_tercer_puesto_rename_grupoa_grupos_grupoa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selecciones',
            old_name='banderacolor',
            new_name='bandera_color',
        ),
        migrations.RemoveField(
            model_name='estadios',
            name='nombreestadio',
        ),
        migrations.RemoveField(
            model_name='grupos',
            name='grupoA',
        ),
        migrations.RemoveField(
            model_name='grupos',
            name='grupoB',
        ),
        migrations.RemoveField(
            model_name='grupos',
            name='grupoC',
        ),
        migrations.RemoveField(
            model_name='grupos',
            name='grupoD',
        ),
        migrations.RemoveField(
            model_name='grupos',
            name='grupoE',
        ),
        migrations.RemoveField(
            model_name='grupos',
            name='grupoF',
        ),
        migrations.RemoveField(
            model_name='grupos',
            name='grupoG',
        ),
        migrations.RemoveField(
            model_name='grupos',
            name='grupoH',
        ),
        migrations.AddField(
            model_name='estadios',
            name='nombre_estadio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='grupos',
            name='categoria',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='grupos',
            name='paises',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
