# Generated by Django 4.1.4 on 2022-12-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMundial', '0010_rename_banderacolor_selecciones_bandera_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitros',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selecciones',
            name='director_tecnico',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
