# Generated by Django 4.1.4 on 2022-12-25 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMundial', '0011_arbitros_edad_jugador_edad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selecciones',
            old_name='seleccion',
            new_name='nombre',
        ),
    ]
