# Generated by Django 4.1.4 on 2022-12-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMundial', '0012_rename_seleccion_selecciones_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fase_grupos',
            old_name='grupo',
            new_name='nombre',
        ),
    ]
