# Generated by Django 4.1.4 on 2022-12-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMundial', '0013_rename_grupo_fase_grupos_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fase_grupos',
            old_name='versus',
            new_name='partido',
        ),
    ]
