# Generated by Django 4.1.4 on 2022-12-28 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMundial', '0014_rename_versus_fase_grupos_partido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fase_grupos',
            old_name='nombre',
            new_name='grupo',
        ),
    ]
